version: "3.5"
services:
  db:
    image: "postgres:11"
    container_name: "postgres"
    volumes:
    - "$PWD/postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: dheeraj
      POSTGRES_PASSWORD: dheeraj
      POSTGRES_DB: my_db
    networks:
      - postgres
  adminer:
    image: adminer
    ports:
      - 7777:8080
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - "$PWD/pgadmin:/root/.pgadmin"
    ports:
      - "9093:80"
    networks:
      - postgres
volumes:
  db:
    driver: local
networks:
  postgres:
    name: postgres-networks
