version: "3"
services:
  mongodb_container:
    image: mongo:latest
    container_name: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - "$PWD/mongodb_data:/data/db"
    networks:
      - notes

  mongo-express:
    image: mongo-express
    container_name: "mongo-express"
    ports:
      - 7779:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on: 
      - mongodb_container
    networks:
      - notes
  
  notes-controller:
    image: dheerajdac/notes_controller:qa01
    ports:
      - "9090:9090"
    networks:
        - notes
    environment:
        - NOTES_SERVICE=notes-service

  notes-service:
    image: dheerajdac/notes_service:qa01
    networks:
      - notes
    environment:
      - NOTES_REPOSITORY=notes-repository

  notes-repository:
    image: dheerajdac/notes_repository:qa01
    networks:
      - notes
    environment:
      - MONGODB_HOST=mongodb_container
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=example
      - MONGODB_NAME=admin
    depends_on: 
      - mongodb_container

volumes:
  mongodb_container:
    driver: local
networks:
  notes:
