version: "3.5"
services:
  mongodb_container:
    image: mongo:latest
    container_name: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - "$PWD/mongodb_data:/data/db"
    networks:
      - mongodb

  mongo-express:
    image: mongo-express
    container_name: "mongo-express"
    ports:
      - 7779:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on: 
      - mongodb_container
    networks:
      - mongodb

volumes:
  mongodb_container:
    driver: local
networks:
  mongodb:
    name: mongodb-networks
