version: "3"
services:
  jenkins:
    image: jenkinsci/blueocean
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
    - webnet
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/jenkins:/var/jenkins_home"
    privileged: true
    user: root

volumes:
  jenkins:
    driver: local

networks:
  webnet: