version: "3.5"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks: 
      - zookeeper
      
networks:
  zookeeper:
    name: zookeeper
