version: "3.9"
services:
    ubuntu:
        image: dheerajdac/ubuntu:java-17
        container_name: ubuntu
        command: sleep infinity
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "./data:/home/ubuntu"
            - "./m2:/home/ubuntu/.m2"
            - type: bind
              source: ./
              target: /workspace
        networks:
          - cassandra
          - kafka
          - zookeeper
          - redis


networks:
  cassandra:
    name: cassandra
  kafka:
    name: kafka
  zookeeper:
    name: zookeeper
  redis:
    name: redis