version: "3.9"
services: 
  cassandra:
    image: cassandra:4.0.3
    container_name: cassandra
    ports:
      - "9042:9042"
    networks: 
      - cassandra

networks: 
  cassandra:
    name: cassandra
  
